// Generated by https://quicktype.io

export interface PokemonListResponse {
    count:     number;
    next?:     string;
    previous?: string;
    results:   PokemonDetail[];
}

export interface PokemonDetail {
    name: string;
    url:  string;
    id:   number;
    img:  string;
}
